### PR TITLE
Add extra phpcs checks

### PR DESCRIPTION
**Pull request by arnoudhgz**
Squiz.WhiteSpace.MemberVarSpacing for enforcing new lines between class
properties.

PSR12.Functions.ReturnTypeDeclaration for how to write return types.

### CODE REVIEW

**Comment by arnoudhgz** [comment]
**Squiz.WhiteSpace.MemberVarSpacing**

Wrong:
```
class Foo
{
    /**
     * @var Test
     */
    private $bar;
    /**
     * @var Test
     */
    private $baz;
}
```

Good:
```
class Foo
{
    /**
     * @var Test
     */
    private $bar;

    /**
     * @var Test
     */
    private $baz;
}
```

**Comment by arnoudhgz** [comment]
**PSR12.Functions.ReturnTypeDeclaration for how to write return types.**

Wrong:
```
public function test():string
{            
}

public function test() :string
{
}

public function test() : string
{
}
```

Good:
```
public function test(): string
{            
}
```

**Comment by ksangers** [comment]
@arnoudhgz I didn't notice you added @igorwulff @ArjenMiedema and @leonhelmus as well. So I won't tag it yet. Can you arrange that the others look at this as well?

**Comment by leonhelmus** [comment]
Checked and approved by me.

**Comment by ArjenMiedema** [comment]
Approved

**Comment by arnoudhgz** [comment]
Seems a logical conclusion @igorwulff

**Comment by arnoudhgz** [comment]
@ksangers can you tag it?

**Pull request merged**
